app/__init__.py
from flask import Flask
import os
import ConfigParser
from logging.handlers import RotatingFileHandler
from flask.ext.pymongo import PyMongo
from flask.ext.cors import CORS
from app.utils.mongo_utils import MongoUtils

# Create MongoDB database object.
mongo = PyMongo()

#Initialize mongo access point
mongo_utils = MongoUtils(mongo)

def create_app():
    # Here we  create flask instance
    app = Flask(__name__)

    # Allow cross-domain access to API.
    #cors = CORS(app, resources={r"/api/*": {"origins": "*"}})

    # Load application configurations
    load_config(app)

    # Configure logging.
    configure_logging(app)

    # Init modules
    init_modules(app)

    # Initialize the app to work with MongoDB
    mongo.init_app(app, config_prefix='MONGO')

    return app


def load_config(app):
    ''' Reads the config file and loads configuration properties into the Flask app.
    :param app: The Flask app object.
    '''
    # Get the path to the application directory, that's where the config file resides.
    par_dir = os.path.join(__file__, os.pardir)
    par_dir_abs_path = os.path.abspath(par_dir)
    app_dir = os.path.dirname(par_dir_abs_path)

    # Read config file
    config = ConfigParser.RawConfigParser()
    config_filepath = app_dir + '/config.cfg'
    config.read(config_filepath)

    app.config['SERVER_PORT'] = config.get('Application', 'SERVER_PORT')
    app.config['MONGO_DBNAME'] = config.get('Mongo', 'DB_NAME')

    # Logging path might be relative or starts from the root.
    # If it's relative then be sure to prepend the path with the application's root directory path.
    log_path = config.get('Logging', 'PATH')
    if log_path.startswith('/'):
        app.config['LOG_PATH'] = log_path
    else:
        app.config['LOG_PATH'] = app_dir + '/' + log_path

    app.config['LOG_LEVEL'] = config.get('Logging', 'LEVEL').upper()


def configure_logging(app):
    ''' Configure the app's logging.
     param app: The Flask app object
    '''

    log_path = app.config['LOG_PATH']
    log_level = app.config['LOG_LEVEL']

    # If path directory doesn't exist, create it.
    log_dir = os.path.dirname(log_path)
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)

    # Create and register the log file handler.
    log_handler = RotatingFileHandler(log_path, maxBytes=250000, backupCount=5)
    log_handler.setLevel(log_level)
    app.logger.addHandler(log_handler)

    # First log informs where we are logging to.
    # Bit silly but serves  as a confirmation that logging works.
    app.logger.info('Logging to: %s', log_path)


def init_modules(app):

    # Import blueprint modules
    from app.mod_main.views import mod_main

    app.register_blueprint(mod_main)

app/mod_main/views.py
from flask import Blueprint , render_template , request , redirect , url_for
from bson import json_util , ObjectId
from app import mongo
from arkep import MyForm

mod_main = Blueprint('main', __name__)


@mod_main.route ('/' ,methods=['GET' , 'POST'])
def index():

    db = mongo.db.arkep

    if request.method == 'GET':
        return render_template("index.html")
    elif request.method =='POST':
        data = request.form.to_dict()
        db.insert(data)
        return render_template("sukses.html")
        #return json_util.dumps(data)
    else:
        return 'bad request'


@mod_main.route('/<string:id>', methods=['GET'])
def get_doc(id):
    db = mongo.db.arkep

    if request.method == 'GET':
        doc = db.find_one({"_id":ObjectId(id)})
        doc_json = json_util.dumps(doc)
        return  render_template('doc.html' , doc=doc)
    else:
        return "bat request"



@mod_main.route('/remove/<string:id>', methods=['GET'])
def remove_doc(id):
    db = mongo.db.arkep
    if request.method == 'GET':
        doc = db.remove({"_id":ObjectId(id)})
        return redirect(url_for('main.lista'))
    else:
        return "bat request"


@mod_main.route('/lista' , methods=['GET'])
def lista():
    dokumentat = mongo.db.arkep.find()
    return render_template('lista.html' , documentat = dokumentat)

app/templates/doc.html
{% extends 'layout.html' %}

{% block content %}
<style>
body{
  background-color: #6DBDD6;
  color: black;
}
#rez{
  padding-top:3%;
  width:800px;
  margin-left:40%;
  font-family: fantasy;
  font-size: 20px;
  text-shadow: 0 1px 0 white;

}
#logo{
  margin-left:35%;
  margin-top:40px;
}
#footer{
   background-color: #0f1d2e;
   letter-spacing: 1.5px;
   padding-top: 0.1px;
   padding-bottom: 5px;
   border-radius:5px;
   padding-right:20px;
 }

   #footercr{
     font-size: 12px;
     color:white;
     text-shadow: 2px 0 2px black;

  }
</style>
<img id="logo" src="{{ url_for('static', filename='images/logo.png')}}"><br><br>
<div id="rez">
Rezultati i kerkuar:
<br><br>
<table id="tael">
{{ doc['emri_ndermarresit'] }}
<br>
{{doc['adresa']}}
<br>
{{ doc['nr_biznesit']}}
<br>
{{ doc['nr_fiskal']}}
<br>
{{ doc['adresa']}}
<br>
{{ doc['nr_tel']}}
<br>
{{ doc['nr_faks']}}
<br>
{{ doc['email']}}
<br>
{{ doc['emri_zyrtarit']}}
<br>
{{ doc['adresa_2']}}
<br>
{{ doc['nr_tel2']}}
<br>
{{ doc['nr_faks2']}}
<br>
{{ doc['email2']}}
<br>
{{ doc['nr_ID']}}
<br>
{{ doc['availability']}}
<br>

</div>

{%block footer%}
{%endblock%}
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<title>Techstitiution</title>
</head>
<body>
	{% block content %}

	{% endblock %}
{%block footer%}

{%endblock%}

</body>
</html>

app/templates/lista.html
<style>
body{
  background-color: #6DBDD6;
}
#tabela{
  margin-left:25%;
  color:black;
}
a{
  color:black;
  text-decoration: none;
}
a:hover{
  color:gray;
}
#h{
  color:black;
  text-shadow: 0 1px 0 white;
}
#fieldset{
  width:1000px;
  margin:auto;
  border:1px solid black;
  box-shadow: 5px 5px 10px 5px black;
}
</style>
<br><br><br><br><br>
<fieldset id="fieldset"> <table style="width:50%" id="tabela">
<tr>
<td id="h"><b>Emri i Ndermarresit<b></td>
<td id="h"><b>Adresa<b></td>
<td id="h"><b>&nbsp;Opsionet<b></td>
</tr>
<tbody>
{% for item in documentat %}
<tr>
<td>{{ item['emri_ndermarresit'] }}</td>
<td>{{ item['adresa'] }}</td>
<td>
<a href="{{url_for('main.get_doc',id=item._id)}}">View&nbsp;</a>
<a href="{{url_for('main.remove_doc',id=item._id)}}">Delete</a>
</td>
</tr>
{% endfor %}
</tbody>
</table>
</fieldset>

app/templates/sukses.html
<html>
<body>
  <style>
body{

  background-color: #6DBDD6;
}
#wrapper{
  width:70%;
  margin:auto;
  background: transparent;
  box-shadow: 2px 2px 5px 2px black;
  color:black;
  font-size:24px;
  text-shadow: 0 1px 1px white;
  text-align: center;
  padding:5px;
}
  </style>
<div style="margin-top:20%" id="wrapper">
<p>  Te dhenat e juaja jane derguar me sukses !! </p>
</div>
</body>
</html>

templates/index.html
<html>
<head>
  <title>ARKEP</title>
</head>
<body>
  <div id="header">
    <h2>ARKEP</h2>
  </div>
  <div class="container">
    <form method="POST">
      <input type="text" name="field1" placeholder="Field 1"/>
      <input type="text" name="field2" placeholder="Field 2"/>
      <input type="submit" value="Register"/>
    </form>
  </div>
</body>
</html>